<?php
use Util\common;
use Util\Check;
class PasswordController extends ControllerBase{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    
    /**
     * 忘记密码
     */
    public function forgetAction(){
        if($this->request->isPost()){
            $token     = $this->request->getPost('token','string','');
            $tokenName = $this->request->getPost('tokenName','string','');
            $account   = $this->request->getPost('account','string','');
            $imgCode   = $this->request->getPost('imgCode','string','');
            
            if (!$this->security->checkToken($tokenName,$token)){
                $this->jsonReturn('','1000','页面超时，请刷新页面重试');
            }
        
            $dataToken['tokenName']  = $this->security->getTokenKey();
            $dataToken['token']      = $this->security->getToken();
        
            if (!Check::VerifyEmail($account)){
                $this->jsonReturn($dataToken,'1002','邮箱格式错误');
            }
        
            $user = ExUsers::itemByEmail($account);
            if(!$user){
                $this->jsonReturn($dataToken,'1004','邮箱未注册');
            }
            
            if (strtolower($imgCode) != $this->session->get('imgCode')){
                $this->jsonReturn($dataToken,'1001','图片验证码错误');
            }
        
            $data['email'] = $account;
            $data['expire']  = time() + (24 * 3600);
            $data['type']  = EmailLogic::RESET_PASSWORD;
        
            $send = EmailLogic::sendMail($data,EmailLogic::RESET_PASSWORD);
        
            $dataToken['d'] = base64_encode(json_encode($data));
        
            if ($send){
                $this->jsonReturn($dataToken);
            } else{
                $this->jsonReturn($dataToken,'100','邮件发送失败');
            }
        }
        $imgCode = common::getCaptcha();
        $this->session->set('imgCode',$imgCode['code']);
        $this->view->setVar('codeUrl',$imgCode['codeUrl']);
    }
    
    /**
     * 设置密码
     */
    public function setAction(){
        if($this->request->isPost()){
            $token     = $this->request->getPost('token','string','');
            $tokenName = $this->request->getPost('tokenName','string','');
            $password  = $this->request->getPost('password','string','');
            $data      = $this->request->getPost('d','string','');
            
            if (!$this->security->checkToken($tokenName,$token)){
                $this->jsonReturn('','1000','页面超时，请刷新页面重试');
            }

            $dataToken['tokenName']  = $this->security->getTokenKey();
            $dataToken['token']      = $this->security->getToken();
            $data = json_decode(base64_decode($data),true);
            $where['email'] = $data['email'];
            $data['password']  = md5(md5($password));

            $save = ExUsers::updataData($where,$data);

            if ($save){
                $this->jsonReturn($dataToken);
            } else{
                $this->jsonReturn($dataToken,'100','密码修改失败请重试');
            }
        }
        $data = $this->request->getQuery('d','string','');
        if($data){
            $data = json_decode(base64_decode($data),true);
            if($data['sign'] != EmailLogic::SIGN){
                $this->_404();
            }
        
            if($data['expire'] < time()){
                $this->_404(); //链接过期
            }
        }else{
            $this->_404();
        }
    }
    
    
    /**
     * 设置成功
     */
    public function successAction(){
    
    }
    
    
    public function sendAction(){
    
    }
    
    
    /**
     * 重新发送密码
     */
    public function sendagainAction(){
        if($this->request->isPost()){
            $token     = $this->request->getPost('token','string','');
            $tokenName = $this->request->getPost('tokenName','string','');
            $data      = $this->request->getPost('d','string','');
    
            if (!$this->security->checkToken($tokenName,$token)){
                $this->jsonReturn('','1000','页面超时，请刷新页面重试');
            }
    
            $dataToken['tokenName']  = $this->security->getTokenKey();
            $dataToken['token']      = $this->security->getToken();
            $data = json_decode(base64_decode($data),true);
            $where['email'] = $data['email'];
            
            $sendData['email'] = $data['email'];
            $sendData['expire']  = time() + (24 * 3600);
            $sendData['type']  = EmailLogic::RESET_PASSWORD;
            
            $send = EmailLogic::sendMail($sendData,EmailLogic::RESET_PASSWORD);
            
            $dataToken['d'] = base64_encode(json_encode($sendData));
            
            if ($send){
                $this->jsonReturn($dataToken);
            } else{
                $this->jsonReturn($dataToken,'100','邮件发送失败');
            }
        }
    }
    
}