<?php
class SecurityController extends ControllerBase{
    
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        if(empty($this->userInfo)){
            self::redirect('/user/login');
        }
    }
    
    public function indexAction(){
        $this->view->setVar('user',$this->userInfo);
    }
    
    public function setLoginPassAction(){
        if($this->request->isPost()){
            $userInfo = $this->userInfo;
    
            $token     = $this->request->getPost('token','string','');
            $tokenName = $this->request->getPost('tokenName','string','');
            if (!$this->security->checkToken($tokenName,$token)){
                $this->jsonReturn('','1000','页面超时，请刷新页面重试');
            }
    
            $dataToken['tokenName']  = $this->security->getTokenKey();
            $dataToken['token']      = $this->security->getToken();
            
            $oldPass  = $this->request->getPost('oldPass','string','');
            
            $checkPassword = UserLogic::checkPassword($userInfo, $oldPass);
            if(!$checkPassword){
                $this->jsonReturn($dataToken,'1007','原始登录密码错误');
            }
            
            $password  = $this->request->getPost('password','string','');
            
            if(!\Util\Check::verifyPassword($password)){
                $this->jsonReturn($dataToken,'1003','密码格式错误');
            }
            
            $save  = ExUsers::saveUserPassword($userInfo['id'],$password);
            if ($save){
                self::deleteSession();
                $this->jsonReturn($dataToken);
            } else{
                $this->jsonReturn($dataToken,'1008','修改失败，请重试');
            }
        }
    }
    
    public function setTradingPassAction(){
        if($this->request->isPost()){
            $userInfo = $this->userInfo;
    
            $token     = $this->request->getPost('token','string','');
            $tokenName = $this->request->getPost('tokenName','string','');
            if (!$this->security->checkToken($tokenName,$token)){
                $this->jsonReturn('','1000','页面超时，请刷新页面重试');
            }
    
            $dataToken['tokenName']  = $this->security->getTokenKey();
            $dataToken['token']      = $this->security->getToken();
    
            $oldPass  = $this->request->getPost('oldPass','string','');
    
            $checkPassword = UserLogic::checkTradingPassword($userInfo, $oldPass);
            if(!$checkPassword){
                $this->jsonReturn($dataToken,'1007','原始交易密码错误');
            }
    
            $password  = $this->request->getPost('password','int','');
            $save  = ExUsers::saveTradingPassword($userInfo['id'],$password);
    
            if ($save){
                $this->jsonReturn($dataToken);
            } else{
                $this->jsonReturn($dataToken,'1008','修改失败，请重试');
            }
        }
        $userInfo = $this->userInfo;
        $user = ExUsers::itemById($userInfo['id']);
        $this->view->setVar('user',$user);
    }
}